//DUT
../hdl/designs/tx/encoder.v
../hdl/designs/tx/PISO.v
../hdl/designs/rx/decoder.v
../hdl/designs/rx/SIPO.v
../hdl/designs/rx/comma_detection.v
../hdl/designs/top_module.v
top_if.sv

//uvm
enums_pkg.sv
transaction_item.sv
enc_dec_sequence.sv
sequencer.sv
enc_driver.sv
enc_dec_monitor.sv
enc_dec_agent.sv
enc_dec_sb.sv
enc_dec_env.sv
enc_dec_test.sv
top.sv
