function hdlverifier_gendll_digital_top(vivado_path)
% hdlverifier_gendll_digital_top is a MATLAB calling wrapper for compiling/elaborating the HDL design
% Generated by Cosimulation Wizard on 24-Jan-2025 11:04:06

% ---- set path info for Vivado executables and kernel libs
lutils('PathPrepend', 'PATH', strcat(vivado_path, '\2019.1\bin\..\lib\win64.o'));
lutils('PathPrepend', 'PATH', strcat(vivado_path, '\2019.1\bin'));

% ---- make system call to Vivado script
[s, r] = system(['vivado -mode tcl < hdlverifier_gendll.tcl'],'-echo');

if (s ~= 0)
    error(message('HDLLink:CosimWizard:ElaborationFailed',r));
end
